// Built-in sample script demonstrating write_text and draw_line.
import type { WhiteboardScript } from "./commandTypes";

export const sampleScript: WhiteboardScript = {
  canvas: {
    width: 1200,
    height: 800,
    background: "#ffffff",
  },
  commands: [
    {
      type: "write_text",
      id: "title",
      text: "AI 白板示例",
      x: 80,
      y: 90,
      fontSize: 44,
      color: "#111111",
      duration: 1200,
    },
    {
      type: "draw_line",
      id: "underline",
      from: [80, 110],
      to: [520, 110],
      color: "#2563eb",
      width: 4,
      duration: 800,
    },
    {
      type: "write_text",
      id: "subtitle",
      text: "这是一个由 JSON 命令控制的白板。",
      x: 80,
      y: 180,
      fontSize: 24,
      color: "#333333",
      duration: 1600,
    },
    {
      type: "write_text",
      id: "section",
      text: "勾股定理",
      x: 80,
      y: 280,
      fontSize: 32,
      color: "#111111",
      duration: 900,
    },
    {
      type: "draw_line",
      id: "tri-base",
      from: [200, 500],
      to: [500, 500],
      color: "#111111",
      width: 3,
      duration: 900,
    },
    {
      type: "draw_line",
      id: "tri-side",
      from: [500, 500],
      to: [500, 320],
      color: "#111111",
      width: 3,
      duration: 900,
    },
    {
      type: "draw_line",
      id: "tri-hyp",
      from: [200, 500],
      to: [500, 320],
      color: "#111111",
      width: 3,
      duration: 1100,
    },
    {
      type: "write_text",
      id: "label-a",
      text: "a",
      x: 340,
      y: 530,
      fontSize: 26,
      color: "#2563eb",
      duration: 400,
    },
    {
      type: "write_text",
      id: "label-b",
      text: "b",
      x: 520,
      y: 420,
      fontSize: 26,
      color: "#2563eb",
      duration: 400,
    },
    {
      type: "write_text",
      id: "label-c",
      text: "c",
      x: 330,
      y: 390,
      fontSize: 26,
      color: "#2563eb",
      duration: 400,
    },
    {
      type: "write_text",
      id: "formula",
      text: "a² + b² = c²",
      x: 80,
      y: 660,
      fontSize: 36,
      color: "#111111",
      duration: 1400,
    },
  ],
};

export const sampleScriptString = JSON.stringify(sampleScript, null, 2);
