// Built-in sample script demonstrating write_text, draw_line, and narration.
import type { WhiteboardScript } from "./commandTypes";

export const sampleScript: WhiteboardScript = {
  canvas: {
    width: 1200,
    height: 800,
    background: "#ffffff",
  },
  commands: [
    {
      type: "write_text",
      id: "title",
      text: "AI 白板示例",
      x: 80,
      y: 90,
      fontSize: 44,
      color: "#111111",
      duration: 1200,
      narration: "同学们好，今天我们用这块白板来讲解一个经典的几何定理。",
    },
    {
      type: "draw_line",
      id: "underline",
      from: [80, 110],
      to: [520, 110],
      color: "#2563eb",
      width: 4,
      duration: 800,
      narration: "我先在标题下面画一条蓝色的下划线，作为强调。",
    },
    {
      type: "write_text",
      id: "subtitle",
      text: "这是一个由 JSON 命令控制的白板。",
      x: 80,
      y: 180,
      fontSize: 24,
      color: "#333333",
      duration: 1600,
      narration: "整块白板的内容,都是由一段 JSON 命令脚本控制的。",
    },
    {
      type: "write_text",
      id: "section",
      text: "勾股定理",
      x: 80,
      y: 280,
      fontSize: 32,
      color: "#111111",
      duration: 900,
      narration: "下面我们进入今天的主题:勾股定理。",
    },
    {
      type: "draw_line",
      id: "tri-base",
      from: [200, 500],
      to: [500, 500],
      color: "#111111",
      width: 3,
      duration: 900,
      narration: "首先,我画一条水平线,作为直角三角形的底边。",
    },
    {
      type: "draw_line",
      id: "tri-side",
      from: [500, 500],
      to: [500, 320],
      color: "#111111",
      width: 3,
      duration: 900,
      narration: "再向上画一条垂直线,这两条边形成一个直角。",
    },
    {
      type: "draw_line",
      id: "tri-hyp",
      from: [200, 500],
      to: [500, 320],
      color: "#111111",
      width: 3,
      duration: 1100,
      narration: "最后连接两端,得到斜边,这就是一个直角三角形。",
    },
    {
      type: "write_text",
      id: "label-a",
      text: "a",
      x: 340,
      y: 530,
      fontSize: 26,
      color: "#2563eb",
      duration: 400,
      narration: "我们把底边记作 a。",
    },
    {
      type: "write_text",
      id: "label-b",
      text: "b",
      x: 520,
      y: 420,
      fontSize: 26,
      color: "#2563eb",
      duration: 400,
      narration: "右边的直角边记作 b。",
    },
    {
      type: "write_text",
      id: "label-c",
      text: "c",
      x: 330,
      y: 390,
      fontSize: 26,
      color: "#2563eb",
      duration: 400,
      narration: "斜边则记作 c。",
    },
    {
      type: "write_text",
      id: "formula",
      text: "a² + b² = c²",
      x: 80,
      y: 660,
      fontSize: 36,
      color: "#111111",
      duration: 1400,
      narration: "勾股定理告诉我们:两条直角边的平方之和,等于斜边的平方。",
    },
  ],
};

export const sampleScriptString = JSON.stringify(sampleScript, null, 2);
